# Generated by Django 3.1.7 on 2021-03-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210323_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_reset_code',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_reset_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
