# Generated by Django 3.1.7 on 2021-03-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_email_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_delete_code',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_delete_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
